### PR TITLE
[IMP] Add new travis testing

### PR DESCRIPTION
**Pull request by lasley**
Depends LasLabs/docker-quality-tools#1

### CODE REVIEW

**Review by tedsalmon — COMMENTED** [review]
Looks like 8.0 is failing to start; is that intended?

**Comment by lasley** [comment]
Yeah Odoo 8 won't allow a run as root. I'm still working on this, changing back to WIP

**Comment by lasley** [comment]
Alright stupid zlib and stupid permissions. I'll nail those in another PR to keep this scope down.

I'm unclear on whether you reviewed this though. Can you provide explicit thumb if it was reviewed, or review it please and thanks

**Review by tedsalmon — APPROVED** [review]
👍  Yup - LGTM!

**Pull request merged**
